### ISSUE TITLE
Use AGPL rather than GPL?

### ISSUE THREAD

**Issue by dhtdht020** [OpenShopChannel/WSC-Web#20]
### Discussed in https://github.com/OpenShopChannel/WSC-Web/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **TheTechRobo** February 20, 2022</sup>
If I'm correct, the plain GPL has a problem for server applications.

Cf. https://www.gnu.org/licenses/why-affero-gpl.en.html:

> Suppose you develop and release a free program under the ordinary GNU GPL. If developer D modifies the program and releases it, the GPL requires him to distribute his version under the GPL too. Thus, if you get a copy of his version, you are free to incorporate some or all of his changes into your own version.
But suppose the program is mainly useful on servers. When D modifies the program, he might very likely run it on his own server and never release copies. Then you would never get a copy of the source code of his version, so you would never have the chance to include his changes in your version. [...]
Using the GNU Affero GPL avoids that outcome. [...] Assuming he has followed the license requirement to let the server's users download the source code of his version, you can do so, and then you can incorporate his changes into your version.

I believe this also affects this program, which can allow people to circumvent the GPL's requirements. (I could be wrong, though.)</div>

**Comment by dhtdht020** [comment]
Hello, @ramblecube, @SketchMaster2001, @spotlightishere, @TheTechRobo.
As the current contributors for this project, I am going to need your combined agreement to relicense it under the AGPLv3.

**Comment by spotlightishere** [comment]
Absolutely in agreement to relicense. Thank you for bringing this to our attention, @TheTechRobo!

**Comment by TheTechRobo** [comment]
I'm in agreement to relicence, too.

**Comment by SketchMaster2001** [comment]
> Hello, @ramblecube, @SketchMaster2001, @spotlightishere, @TheTechRobo.
> As the current contributors for this project, I am going to need your combined agreement to relicense it under the AGPLv3.

I am in agreement as well.

**Comment by ramblecube** [comment]
Sounds good to me- yes.

**Comment by TheTechRobo** [comment]
I think that's everyone?

**Comment by spotlightishere** [comment]
Complete as of 3eaaa8a7b2d7b5e6fc182bd371b500733c43d2ec. Thank you!
