### ISSUE TITLE
python 3 being weird

### ISSUE THREAD

**Issue by purpelpower** [OpenShopChannel/WSC-Web#22]
ok uhm why does flask not work?

logs:
C:\Users\purpe\Desktop\WSC-Web-master>python3 app.py
Traceback (most recent call last):
  File "C:\Users\purpe\Desktop\WSC-Web-master\app.py", line 1, in <module>
    from flask import Flask, render_template, request, redirect, Response
ModuleNotFoundError: No module named 'flask'

C:\Users\purpe\Desktop\WSC-Web-master>pip3 install flask
Requirement already satisfied: flask in c:\python310\lib\site-packages (2.0.3)
Requirement already satisfied: itsdangerous>=2.0 in c:\python310\lib\site-packages (from flask) (2.1.0)
Requirement already satisfied: click>=7.1.2 in c:\python310\lib\site-packages (from flask) (8.0.4)
Requirement already satisfied: Werkzeug>=2.0 in c:\python310\lib\site-packages (from flask) (2.0.3)
Requirement already satisfied: Jinja2>=3.0 in c:\python310\lib\site-packages (from flask) (3.0.3)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from click>=7.1.2->flask) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from Jinja2>=3.0->flask) (2.1.0)
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\purpe\Desktop\WSC-Web-master>

**Comment by purpelpower** [comment]
update: i think i fixed it but now im stuck on the certs part as it doesnt generate the 2 required certs

**Comment by TheTechRobo** [comment]
https://github.com/openshopchannel/WSC-Patcher should generate the certs ?

You rename server.key to key.pem and server.pem to cert.pem, IIRC.

**Comment by purpelpower** [comment]
C:\Users\purpe\Desktop\WSC-Web-master>python app.py
C:\Users\purpe\Desktop\WSC-Web-master\app.py:191: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
Traceback (most recent call last):
  File "C:\Users\purpe\Desktop\WSC-Web-master\app.py", line 194, in <module>
    context.load_cert_chain('cert.pem', 'key.pem')
ssl.SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3883)

C:\Users\purpe\Desktop\WSC-Web-master>

yeah no

**Comment by spotlightishere** [comment]
>     context.load_cert_chain('cert.pem', 'key.pem')
> 
> ssl.SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3883)

This specific issue is due to OpenShopChannel/WSC-Patcher#2. If possible, please try out its changes!

**Comment by spotlightishere** [comment]
This issue should be resolved as of [WSC-Patcher v1.2.0](https://github.com/OpenShopChannel/WSC-Patcher/releases/tag/v1.2.0) - please open an issue on that repo if you encounter similar issues in the future!
