### ISSUE TITLE
Shop failing to connect to WSC-Web

### ISSUE THREAD

**Issue by Sonic4Tails** [OpenShopChannel/WSC-Web#24]
is it ok if the connecting screen never appears
and then returns the error 209601

**Comment by spotlightishere** [comment]
The error code 209601 means that the channel timed out while loading (i.e. connection dropped, [`shop.connecting`](https://docs.oscwii.org/wii-shop-channel/js/shop#connecting-example) never accessed, etc.). It might be worth checking that that you can access https://127.0.0.1:443 (or https://oss-auth.a.taur.cloud:443) locally to verify that the server is running!

**Comment by Sonic4Tails** [comment]
I can access both endpoints and i havent edited the branch itself so idk
why it does say that

Op za 20 aug. 2022 19:20 schreef Spotlight ***@***.***>:

**Comment by spotlightishere** [comment]
How are you running the channel? If you've patched with a base domain of `a.taur.cloud`, you'll want to use Dolphin locally (as it resolves to 127.0.0.1). Additionally, if you're attempting to test via a real console, you'll need to configure a domain for access - see the [WSC-Patcher README](https://github.com/OpenShopChannel/WSC-Patcher#setup) for more information.

**Comment by Sonic4Tails** [comment]
Im running the channel via dolphin, patched with the a.taur.cloud domain
and running it via the wii menu

Op za 20 aug. 2022 20:24 schreef Spotlight ***@***.***>:

**Comment by TheTechRobo** [comment]
Are you running WSC-Web on localhost?

**Comment by Sonic4Tails** [comment]
Yes

Op za 20 aug. 2022 21:54 schreef TheTechRobo ***@***.***>:

**Comment by Sonic4Tails** [comment]
actually does it mean something that when accessing the url in the browser it says ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by spotlightishere** [comment]
>  Also worth to add is that i requests https://oss-auth.a.taur.cloud/ 5 times and then it hangs until it gives me an error message

Ah - that does help to diagnose the issue. Are you running via `flask run` directly?

If so, the default web server provided by Flask utilizes HTTP/1.0, which Opera on the Wii does not support (producing that odd request-five-times behavior). Within `app.py`, we enforce HTTP/1.1:
https://github.com/OpenShopChannel/WSC-Web/blob/a8092f1af9e43cd7d57e77c7f9bd2b75f7c8b57c/app.py#L191

Perhaps we should be smarter here and enforce HTTP/1.1 if the application is running in development mode.

**Comment by Sonic4Tails** [comment]
No im running it via "python app.py"

Op zo 21 aug. 2022 20:19 schreef Spotlight ***@***.***>:

**Comment by Sonic4Tails** [comment]
uhhh i still need help

**Comment by Sonic4Tails** [comment]
anyways maybe this means something as when starting the server it says the following:

C:\Users\purpe\Documents\WSC-Web-master\app.py:192: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on https://127.0.0.1:443
Press CTRL+C to quit
 * Restarting with stat
C:\Users\purpe\Documents\WSC-Web-master\app.py:192: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
 * Debugger is active!
 * Debugger PIN: 118-910-302

**Comment by spotlightishere** [comment]
Thank you for your patience - things have been extraordinarily busy recently :) Today, I was able to sit down and properly diagnose this issue.

As mentioned previously, Opera struggles with HTTP/1.0 itself. However, Opera on the Wii struggles also struggles with the HTTP header `Connection` being set to `close`. I do not understand why this is, nor enough about Opera to more properly debug it. This issue affects both HTTP/1.0 and HTTP/1.1, and again presents itself in the form of Opera creating 5 requests and then eventually timing out.

Previously, we set HTTP/1.1, and relied on no `Connection` header being sent. However, with Werkzeug 2.1.2 (released 28 April, 2022), [`Connection` is now set to `close`](https://github.com/pallets/werkzeug/blob/5dff30f8191589ddc5faf1aa2f445fe30befcbcf/src/werkzeug/serving.py#L286-L290):
```py
# Always close the connection. This disables HTTP/1.1
# keep-alive connections. They aren't handled well by
# Python's http.server because it doesn't know how to
# drain the stream before the next request line.
self.send_header("Connection", "close")
```
(For further discussion, see pallets/werkzeug#2397 - seems like a fair solution to avoid issues on their part.)

However, even if we attempt to hijack `app.after_request` and set `Connection` to `keep-alive` prior, we'll end up with
```
Connection: keep-alive
Connection: close
```
...which doesn't work, as the second header's value is read and utilized.


---
Unfortunately, this console will always boil down to a nonsensical bundle of hacks, so we need to rely on the old behavior. For the time being, I've committed 4961a0d876152b64009657f6eae4d0efb5f528c1 to resolve this by hackily overriding [BaseHTTPRequestHandler.send_header](https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.send_header) itself, which may very well break in future Python versions.

In the future, we shouldn't support running this repository directly with SSL. Instead, we should recommend a setup with nginx in front, as it properly manages `Connection: keep-alive` for us. (This environment should definitely bundle in [WiiSOAP](https://github.com/OpenShopChannel/WiiSOAP), as that will be increasingly a requirement of this repository in the future.)

**Comment by Sonic4Tails** [comment]
when i have the time i´ll check if that works


Op wo 24 aug. 2022 om 02:22 schreef Spotlight ***@***.***>:
